SNMP:
  oid: "1.3.6.1.4.1.674.10892.5.3.1.2.0"
  SNMPUSER:
    NAME: "snmpv3user"
    PASSWORD: "calvinkey"

SMS:
  api: "http://192.168.206.149:18005/sendMessage"

SMTP:
  host: "smtp.chinadaas.com"
